Contact page
nfqakademija/Globalus pull request #16
Opened 2016-12-04 15:23 UTC by DziugasDraksas

2016-12-04 17:15 UTC, ArnoldasMilkus commented on src/AppBundle/Resources/views/Test/success.html.twig
> +        <script>document.ready(window.setTimeout(location.href = "http://192.168.4.100/app_dev.php/",10));</script>
href will be needed to be changed for server

2016-12-05 07:12 UTC, spaivaras requested changes

2016-12-05 07:12 UTC, spaivaras commented on src/AppBundle/Controller/ContactController.php
> +//        $contact->setDueDate(new \DateTime('tomorrow'));
No point on commented out code, Also please check PSR-2 standards

2016-12-05 07:12 UTC, spaivaras commented on src/AppBundle/Controller/ContactController.php
> +}
No new line at the file and

2016-12-05 07:12 UTC, spaivaras commented on src/AppBundle/Entity/Contact.php
> +    private $email;
Why not add validators? so that form would actually check user input

2016-12-05 07:12 UTC, spaivaras commented on src/AppBundle/Resources/views/Contact/contact.html.twig
> +    <style>
Please add style sheets to a stylesheet file, not template

2016-12-06 11:19 UTC, spaivaras commented
There is a new pr merged to master witch fixed global psr2 problems, it could be beneficial to merge master back to this branch

2016-12-06 13:40 UTC, merged